### ISSUE TITLE
drone server failed to start on raspberry pi

### ISSUE THREAD

**Issue by vimagick** [armswarm/drone#1]
I'm try to run drone on my raspberry pi 3B.
drone server failed to start, and print error.

```bash
$ docker run --rm -it --entrypoint sh quay.io/armswarm/drone:0.7
/ # /drone server
ERRO[0000] sql: unknown driver "sqlite3" (forgotten import?)
FATA[0000] database connection failed
```

**Comment by yangxuan8282** [comment]
@alkar 
would you mind share how to setup drone on raspberry pi?

**Comment by alkar** [comment]
Hi, I completely missed notification for this issue it seems.

@vimagick I think the version of the image you were trying to run was quite broken. That being said, I also think you wouldn't be able to use it with the `sqlite3` driver because it's being compiled without cgo. Try overriding that as documented in the official drone docs. The image I pushed this morning should work fine as I'm running it myself.

@yangxuan8282 you should run the server & agent images (follow the official drone instructions on how to configure them). I run those two along with a postgres container for the database.

The images in dockerhub are quite of date, please the ones found in https://quay.io/organization/armswarm

**Comment by vimagick** [comment]
@alkar Thank you :)

**Comment by chapp-hk** [comment]
@alkar 
I've pulled the docker image with "docker pull quay.io/armswarm/drone"
But it still giving out these error message

time="2017-09-24T14:23:50Z" level=error msg="sql: unknown driver \"sqlite3\" (forgotten import?)" 
time="2017-09-24T14:23:50Z" level=fatal msg="database connection failed"

**Comment by alkar** [comment]
@chapp-hk my previous comment on the lack of cgo stands with this image as well. The drone binary is built without cgo, which is required for sqlite3 AFAIK. Try overriding the database configuration (using environment variable as per official docs) to point to a MySQL or PostgreSQL instance.

This container is built in exactly the same way as it's done upstream so I believe you'd get the same error there too.
